name: haimdall
description: "AWD Project"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.4+30

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  custom_refresh_indicator: ^4.0.1
  device_info_plus: ^10.1.2
  equatable: ^2.0.5
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  firebase_crashlytics: ^4.1.0
  flutter_email_sender: ^6.0.3
  flutter_local_notifications: ^17.2.3
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  klc: ^0.1.0
  location: ^7.0.0
  logger: ^2.4.0
  package_info_plus: ^8.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.2
  smooth_page_indicator: ^1.2.0+3
  syncfusion_flutter_pdfviewer: ^27.1.51
  syncfusion_flutter_core: ^27.1.51
  table_calendar: ^3.1.2
  tuple: ^2.0.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tutorial/bd/
    - assets/images/tutorial/en/
    - assets/images/tutorial/kh/
    - assets/images/tutorial/ko/
    - assets/images/tutorial/vi/
    - assets/icons/
    - assets/fonts/
    - assets/pdfs/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansKR-Black.ttf
          weight: 900
