final koString = {
  'login_desc': '디지털 농업의 시작\n헤임달로 간편하게 기록하세요!',
  'login_desc_sns': 'SNS 계정으로 로그인',
  'select_language': 'Language',
  'select_language_title': '언어 선택',
  'select_language_error_message': '국가와 언어를 선택해 주세요!',
  'ok': '확인',
  'cancel': '취소',
  'terms_page_title': '개인정보 약관 동의',
  'terms_check_required': '약관/개인정보 처리 방침 뷰 동의(필수)',
  'terms_check_service': '서비스 이용 약관(필수)',
  'terms_next_error_message': '약관 동의 후 다음으로 이동해 주세요.',
  'terms_privacy': '개인정보 처리 방침',
  'terms_service': '이용 약관',
  'next': '다음',
  'awd_title': 'AWD 자세히 알려드릴게요!',
  'signup_title': '가입 정보 입력',
  'signup_input_name': '이름을 입력해 주세요.',
  'signup_input_name_hint': '이름 입력',
  'signup_input_phone': '휴대폰 번호를 입력해 주세요.',
  'signup_input_phone_hint': '휴대전화 번호 입력',
  'signup_input_email': '이메일을 입력해 주세요.',
  'signup_input_email_hint': '이메일 입력',
  'input_error': '필수 항목을 모두 입력해 주세요.',
  'input_warning_back': '작성한 내용이 삭제됩니다.\n계속하시겠습니까?',
  'yes': '네',
  'no': '아니요',
  'signup_project_title': '프로젝트 선택',
  'signup_project_desc': '원하시는 프로젝트를 선택해 주세요.',
  'signup_project_desc_point': '(단일 선택만 가능합니다.)',
  'signup_project_select_hint': '프로젝트를 선택해 주세요.',
  'signup_waiting_desc1': '잠시만\n기다려주세요!',
  'signup_waiting_desc2': '관리자 승인 중입니다!',
  'signup_denied_desc1': '관리자 승인이\n거절되었습니다.',
  'signup_denied_desc2': '다시 등록해 주세요.',
  'signup_denied_request_approve': '재승인 요청',
  'tutorial_video': '튜토리얼 영상 보기',
  'skip': '건너뛰기',
  'farmland_list_title': '농지 리스트',
  'farmland_add': '농지 추가',
  'farmland_add_title': '농지 정보 입력',
  'farmland_owner_name': '참여 농업인 이름',
  'farmland_owner_name_desc': '(변경이 불가합니다. 신중히 작성해 주세요!)',
  'farmland_owner_name_input_hint': '참여 농업인 이름을 입력해 주세요.',
  'farmland_area': '농지 면적',
  'farmland_area_input_hint': '농지 면적(ha)을 입력해 주세요.',
  'farmland_area_unit': 'ha',
  'take_picture': '사진촬영',
  'latitude': '위도',
  'longitude': '경도',
  'record_title': '기록해요.',
  'record_pump': '물대기',
  'record_drain_water': '물빼기',
  'record_fertilizer': '비료 기록',
  'record_pesticide': '농약 기록',
  'record_harvest': '수확량 기록',
  'record_diary': '일지 작성',
  'record_diary_option': '하루 메모 (선택)',
  'record_diary_hint': '내용 입력 (최대 3000자)',
  'record_done': '기록 완료',
  'record_calendar_lunar': '음력 표시',
  'record_calendar_event_pump_on': '물대기 시작',
  'record_calendar_event_pump_off': '물대기 종료',
  'record_calendar_event_start_drain_water': '물빼기 시작',
  'record_calendar_event_end_drain_water': '물빼기 끝',
  'record_input_data': '농사 정보 입력',
  'my_page_name_title': '님,',
  'my_page_hello': '안녕하세요!',
  'my_page_menu_awd_change': '물빼기 일정 변경',
  'my_page_menu_faq': 'FAQ',
  'my_page_menu_terms_service': '서비스 이용 약관',
  'my_page_menu_terms_privacy': '개인정보 처리방침',
  'my_page_menu_qna': '문의하기',
  'my_page_menu_awd_edu': 'AWD 교육 자료',
  'my_page_menu_tutorial': '튜토리얼',
  'my_page_menu_language': '언어 설정',
  'my_page_menu_app_version': '버전 정보',
  'my_page_menu_logout': '로그아웃',
  'my_page_menu_withdraw': '회원탈퇴',
  'progress_title': 'AWD 진행 현황',
  'progress_overall': '전체 과정',
  'progress_planting': 'Planting',
  'progress_1st_awd': '1st AWD',
  'progress_2nd_awd': '2nd AWD',
  'progress_harvest': 'Harvest',
  'progress_record_pump': '물대기',
  'progress_record_photo': '사진 촬영',
  'progress_finish_project': '프로젝트 종료',
  'progress_finish_project_popup_message': '프로젝트를\n종료하시겠습니까?',
  'input': '입력하기',
  'logout_desc': '로그아웃 하시겠습니까?',
  'logout': '로그아웃',
  'withdraw': '회원탈퇴',
  'withdraw_desc': '회원탈퇴 하시겠습니까?',
  'input_rice_planting_title': '농사 정보 입력',
  'input_rice_planting_date': '모내기 일자를 선택해 주세요.',
  'input_rice_planting_date_hint': '모내기 일자를 선택해 주세요.',
  'input_rice_planting_type': '모내기 방식을 선택해 주세요.',
  'input_rice_planting_type_hint': '모내기 방식을 선택해 주세요.',
  'input_rice_planting_rice_cultivar': '벼 품종을 선택해 주세요.',
  'input_rice_planting_rice_cultivar_hint': '벼 품종을 선택해 주세요.',
  'input_pump_planting_title': '물대기 일정 등록',
  'input_pump_planting_index': '물대기 ON/OFF {count}차 일정',
  'input_pump_planting_hint': '물대기 일자 선택',
  'input_pump_error_date': '일정을 확인해주세요.\n일정은 순차적으로 입력해주세요.',
  'input_pump_error_maximum': '일정은 최대 5개까지만 추가할 수 있습니다.',
  'input_drain_water_planting_title': '물빼기 일정 등록',
  'input_drain_water_planting_select_hint': '물빼기 일자 선택',
  'input_drain_water_planting_index': '물빼기 {count}차 일정',
  'record_confirm_message': '입력 후에는 변경이 불가합니다.\n계속하시겠습니까?',
  'record_pesticide_title': '농약을 기록해 주세요!',
  'record_pesticide_input_hint': '농약 종류를 선택해 주세요.',
  'record_pesticide_type': '농약 종류',
  'record_pesticide_usage': '농약 사용량',
  'record_pesticide_usage_input_hint': '농약 사용량을 입력해 주세요.',
  'record_harvest_title': '수확량을 기록해주세요!',
  'record_harvest_input_hint': '수확량을 입력해 주세요.',
  'record_fertilizer_title': '비료를 기록해 주세요!',
  'record_fertilizer_type': '비료 종류',
  'record_fertilizer_input_hint': '비료 종류를 선택해 주세요.',
  'record_fertilizer_usage': '비료 사용량',
  'record_fertilizer_usage_input_hint': '비료 사용량을 입력해 주세요.',
  'record_drain_water_title': '물 빼기 사진 인증',
  'harvest': '수확량',
  'cannot_modified': '수정할 수 없습니다.',
  'error_select_date_message': '날짜를 선택해 주세요.',
  'permission_error_message': '권한을 확인해 주세요.',
  'move_setting': '설정 이동',
  'time': '시각',
  'take_picture2': '사진 촬영',
  'record_pump_on_message': '상태를 on으로 변경하시겠습니까?\n추후 변경이 불가합니다.',
  'record_pump_off_message': '상태를 off로 변경하시겠습니까?\n추후 변경이 불가합니다.',
  'change_request_history_title': '변경 요청 내역',
  'change_request_history_empty': '변경 요청 내역이 없습니다.',
  'tab_home': '홈',
  'tab_progress': '진행 현황',
  'tab_mypage': '마이페이지',
  'record_diary_empty': '작성된 일지가 없습니다.',
  'schedule_change_request_title': '일정 변경',
  'schedule_change_request_reason': '변경 사유',
  'schedule_change_request_reason_hint': '내용 입력 (최대 3,000자)',
  'progress_error_message': '진행 상황을 확인해 주세요.',
  'record_diary_confirm_message': '일지를 작성하시겠습니까?',
  'my_page_menu_notification': '알림 설정',
  'exception_unexpected': '알 수 없는 에러가 발생했습니다.',
  'exception_network': '네트워크 연결 상태를 확인해주세요.',
  'exception_not_found_user': '사용자 정보를 찾을 수 없습니다.',
  'my_page_menu_pump_change': '물대기 일정 변경',
  'my_page_menu_pump_change_history': '물대기 일정 변경 내역',
  'farmland_status_pending': '승인 중',
  'farmland_status_rejected': '승인거절',
  'farmland_status_photo_required': '사진필요',
  'farmland_status_approved': '승인완료',
  'farmland_status_completed': '수행완료',
  'change_request_status_pending': '승인 중',
  'change_request_status_approved': '승인완료',
  'change_request_status_rejected': '승인거절',
  'hand_planting': '손 모내기',
  'machine_planting': '기계식 모내기',
  'my_page_menu_awd_change_history': '물빼기 일정 변경 내역',
};
