final enString = {
  'login_desc': 'The Beginning of Digital Agriculture\nRecord Easily with Haimdall!',
  'login_desc_sns': 'Login with SNS Account',
  'select_language': 'Language',
  'select_language_title': 'Language Selection',
  'select_language_error_message': 'Please select a country and language!',
  'ok': 'Confirm',
  'cancel': 'Cancel',
  'terms_page_title': 'Agree to the Privacy Policy',
  'terms_check_required': 'Agree to Terms and Conditions/Privacy Policy (Required)',
  'terms_check_service': 'Terms of Service (Required)',
  'terms_next_error_message': 'Please proceed after agreeing to the terms.',
  'terms_privacy': 'Privacy Policy',
  'terms_service': 'Terms and Conditions',
  'next': 'Next',
  'awd_title': 'Let me tell you more about AWD!',
  'signup_title': 'Enter Signup Information',
  'signup_input_name': 'Please enter your name.',
  'signup_input_name_hint': 'Name Input',
  'signup_input_phone': 'Please enter your mobile phone number.',
  'signup_input_phone_hint': 'Mobile Phone Number Input',
  'signup_input_email': 'Please enter your email address.',
  'signup_input_email_hint': 'Email Input',
  'input_error': 'Please fill in all the required fields.',
  'input_warning_back': 'The content you’ve written will be deleted.\nDo you wish to continue?',
  'yes': 'Yes',
  'no': 'No',
  'signup_project_title': 'Select Project',
  'signup_project_desc': 'Please select the desired project.',
  'signup_project_desc_point': '(Only single selection is allowed.)',
  'signup_project_select_hint': 'Please select a project.',
  'signup_waiting_desc1': 'Please wait\nfor a moment!',
  'signup_waiting_desc2': 'Approval from the Administrator is in Progress!',
  'signup_denied_desc1': 'Administrator approval has been rejected',
  'signup_denied_desc2': 'Please register again.',
  'signup_denied_request_approve': 'Request for Re-approval',
  'tutorial_video': 'Watch Tutorial Video',
  'skip': 'Skip',
  'farmland_list_title': 'Farmland List',
  'farmland_add': 'Add Farmland',
  'farmland_add_title': 'Enter Farmland Information',
  'farmland_owner_name': "Participating Farmer's Name",
  'farmland_owner_name_desc': '(Changes are not allowed. Please fill it out carefully!)',
  'farmland_owner_name_input_hint': 'Please enter the name of the participating farmer.',
  'farmland_area': 'Farmland Area',
  'farmland_area_input_hint': 'Please enter the farmland area (ha).',
  'farmland_area_unit': 'ha',
  'take_picture': 'Take a Photo',
  'latitude': 'Latitude',
  'longitude': 'Longitude',
  'record_title': 'Record it.',
  'record_pump': 'Watering record ',
  'record_drain_water': 'Water Drainage',
  'record_fertilizer': 'Fertilizer Record',
  'record_pesticide': 'Pesticide Record',
  'record_harvest': 'Yield Record',
  'record_diary': 'Diary Entry',
  'record_diary_option': 'Daily Note (Optional)',
  'record_diary_hint': 'Enter Content (Up to 3000 characters)',
  'record_done': 'Recording Complete',
  'record_calendar_lunar': 'Lunar Calendar Display',
  'record_calendar_event_pump_on': 'Water in',
  'record_calendar_event_pump_off': 'Water out',
  'record_calendar_event_start_drain_water': 'Start draining water',
  'record_calendar_event_end_drain_water': 'End draining water',
  'record_input_data': 'Enter farming information',
  'my_page_name_title': 'Sir/Madam ',
  'my_page_hello': 'Hello!',
  'my_page_menu_awd_change': 'Water Drainage Schedule Change',
  'my_page_menu_faq': 'FAQ',
  'my_page_menu_terms_service': 'Terms of Service',
  'my_page_menu_terms_privacy': 'Privacy Policy',
  'my_page_menu_qna': 'Contact Us',
  'my_page_menu_awd_edu': 'AWD Educational Materials',
  'my_page_menu_tutorial': 'Tutorial',
  'my_page_menu_language': 'Language',
  'my_page_menu_app_version': 'Version Information',
  'my_page_menu_logout': 'Logout',
  'my_page_menu_withdraw': 'Delete Account',
  'progress_title': 'AWD progress',
  'progress_overall': 'Entire process',
  'progress_planting': 'Planting',
  'progress_1st_awd': '1st AWD',
  'progress_2nd_awd': '2nd AWD',
  'progress_harvest': 'Harvest',
  'progress_record_pump': 'Watering record',
  'progress_record_photo': 'Taking a photo',
  'progress_finish_project': 'End project',
  'progress_finish_project_popup_message': 'Do you want to end the project?',
  'input': 'Enter',
  'logout_desc': 'Do you want to log out?',
  'logout': 'Log out',
  'withdraw': 'Delete account',
  'withdraw_desc': 'Do you want to delete your account?',
  'input_rice_planting_title': 'Enter farming information',
  'input_rice_planting_date': 'Please select the rice transplanting date.',
  'input_rice_planting_date_hint': 'Please select the rice transplanting date.',
  'input_rice_planting_type': 'Please select the rice transplanting method.',
  'input_rice_planting_type_hint': 'Please select the rice transplanting method.',
  'input_rice_planting_rice_cultivar': 'Please select the rice variety.',
  'input_rice_planting_rice_cultivar_hint': 'Please select the rice variety.',
  'input_pump_planting_title': 'Register watering schedule',
  'input_pump_planting_index': 'Watering ON/OFF {count}th schedule',
  'input_pump_planting_hint': 'Select watering date',
  'input_pump_error_date': 'Please check the schedule. \n Enter the schedule in order.',
  'input_pump_error_maximum': 'You can add up to 5 schedules only.',
  'input_drain_water_planting_title': 'Register draining schedule',
  'input_drain_water_planting_select_hint': 'Select draining date',
  'input_drain_water_planting_index': 'Draining {count}th schedule',
  'record_confirm_message': 'Changes are not allowed after entry.\n Do you want to proceed?',
  'record_pesticide_title': 'Please record pesticide use!',
  'record_pesticide_input_hint': 'Please select the pesticide type.',
  'record_pesticide_type': 'Pesticide type',
  'record_pesticide_usage': 'Pesticide usage',
  'record_pesticide_usage_input_hint': 'Please enter the pesticide usage.',
  'record_harvest_title': 'Please record the yield!',
  'record_harvest_input_hint': 'Please enter the yield.',
  'record_fertilizer_title': 'Please record fertilizer usage!',
  'record_fertilizer_type': 'Fertilizer type',
  'record_fertilizer_input_hint': 'Please select the fertilizer type.',
  'record_fertilizer_usage': 'Fertilizer usage',
  'record_fertilizer_usage_input_hint': 'Please enter the fertilizer usage.',
  'record_drain_water_title': 'Water draining photo verification',
  'harvest': 'Yield',
  'cannot_modified': 'Cannot be modified.',
  'error_select_date_message': 'Please select a date.',
  'permission_error_message': 'Please check permissions.',
  'move_setting': 'Go to settings',
  'time': 'Time',
  'take_picture2': 'Take a photo',
  'record_pump_on_message': 'Do you want to change the status to on?\n Changes will not be allowed later.',
  'record_pump_off_message': 'Do you want to change the status to off?\n Changes will not be allowed later.',
  'change_request_history_title': 'Change request history',
  'change_request_history_empty': 'No change requests found.',
  'tab_home': 'Home',
  'tab_progress': 'Progress',
  'tab_mypage': 'My Page',
  'record_diary_empty': 'No logs have been written.',
  'schedule_change_request_title': 'Change schedule',
  'schedule_change_request_reason': 'Reason for change',
  'schedule_change_request_reason_hint': 'Enter content (up to 3,000 characters)',
  'progress_error_message': 'Please check the progress.',
  'record_diary_confirm_message': 'Do you want to write a log?',
  'my_page_menu_notification': 'Notification settings',
  'exception_unexpected': 'An unknown error has occurred.',
  'exception_network': 'Please check your network connection.',
  'exception_not_found_user': 'User information cannot be found.',
  'my_page_menu_pump_change': 'Irrigation Schedule Change',
  'my_page_menu_pump_change_history': 'Irrigation Schedule Change History',
  'farmland_status_pending': 'Pending Approval',
  'farmland_status_rejected': 'Approval Rejected',
  'farmland_status_photo_required': 'Photo Required',
  'farmland_status_approved': 'Approval Completed',
  'farmland_status_completed': 'Task Completed',
  'change_request_status_pending': 'Pending Approval',
  'change_request_status_approved': 'Approval Completed',
  'change_request_status_rejected': 'Approval Rejected',
  'hand_planting': 'Hand Planting',
  'machine_planting': 'Machine Planting',
  'my_page_menu_awd_change_history': 'Water Drainage Schedule Change History',
};
