final khString = {
  'login_desc': 'ការចាប់ផ្តើមនៃកសិកម្មឌីជីថល\nកត់ត្រាយ៉ាងងាយស្រួលជាមួយ Haimdall!',
  'login_desc_sns': 'ចូលដោយប្រើគណនី SNS',
  'select_language': 'Language',
  'select_language_title': 'ការជ្រើសរើសភាសា',
  'select_language_error_message': 'សូមជ្រើសរើសប្រទេស និងភាសា!',
  'ok': 'បញ្ជាក់',
  'cancel': 'បោះបង់',
  'terms_page_title': 'យល់ព្រមចំពោះគោលការណ៍ឯកជនភាព',
  'terms_check_required': 'យល់ព្រមតាមលក្ខខណ្ឌ/គោលការណ៍ឯកជនភាព (ទាមទារ)',
  'terms_check_service': 'លក្ខខណ្ឌនៃសេវាកម្ម (ទាមទារ)',
  'terms_next_error_message': 'សូមបន្តបន្ទាប់ពីយល់ព្រមតាមលក្ខខណ្ឌ។',
  'terms_privacy': 'គោលការណ៍ឯកជនភាព',
  'terms_service': 'លក្ខខណ្ឌ',
  'next': 'បន្ទាប់',
  'awd_title': 'ខ្ញុំសូមប្រាប់អ្នកបន្ថែមអំពី AWD!',
  'signup_title': 'បញ្ចូលព័ត៌មានចុះឈ្មោះ',
  'signup_input_name': 'សូមបញ្ចូលឈ្មោះរបស់អ្នក។',
  'signup_input_name_hint': 'ការបញ្ចូលឈ្មោះ',
  'signup_input_phone': 'សូមបញ្ចូលលេខទូរស័ព្ទរបស់អ្នក',
  'signup_input_phone_hint': 'ការបញ្ចូលលេខទូរស័ព្ទចល័ត',
  'signup_input_email': 'សូមបញ្ចូលអាសយដ្ឋានអ៊ីមែលរបស់អ្នក',
  'signup_input_email_hint': 'ការបញ្ចូលអ៊ីមែល',
  'input_error': 'សូមបំពេញគ្រប់វាលដែលត្រូវការ',
  'input_warning_back': 'ខ្លឹមសារដែលអ្នកបានសរសេរនឹងត្រូវបានលុប។\nតើអ្នកចង់បន្តទេ?',
  'yes': 'បាទ',
  'no': 'ទេ',
  'signup_project_title': 'ជ្រើសរើសគម្រោង',
  'signup_project_desc': 'សូមជ្រើសរើសគម្រោងដែលចង់បាន។',
  'signup_project_desc_point': '(មានតែជម្រើសតែមួយប៉ុណ្ណោះត្រូវបានអនុញ្ញាត។ )',
  'signup_project_select_hint': 'សូមជ្រើសរើសគម្រោងមួយ។',
  'signup_waiting_desc1': 'សូមរង់ចាំ\nមួយភ្លែត!',
  'signup_waiting_desc2': 'ការយល់ព្រមពីអ្នកគ្រប់គ្រងកំពុងដំណើរការ!',
  'signup_denied_desc1': 'ការយល់ព្រមពីអ្នកគ្រប់គ្រងត្រូវបានបដិសេធ',
  'signup_denied_desc2': 'សូមចុះឈ្មោះម្តងទៀត',
  'signup_denied_request_approve': 'ស្នើសុំការយល់ព្រមឡើងវិញ',
  'tutorial_video': 'មើលវីដេអូបង្រៀន',
  'skip': 'រំលង',
  'farmland_list_title': 'បញ្ជីដីស្រែចម្ការ',
  'farmland_add': 'បន្ថែមដីស្រែចម្ការ',
  'farmland_add_title': 'បញ្ចូលព័ត៌មានដីស្រែចំការ',
  'farmland_owner_name': 'ឈ្មោះកសិករដែលចូលរួម',
  'farmland_owner_name_desc': '(ការផ្លាស់ប្ដូរមិនត្រូវបានអនុញ្ញាតទេ។ សូមបំពេញវាដោយប្រុងប្រយ័ត្ន!)',
  'farmland_owner_name_input_hint': 'សូមបញ្ចូលឈ្មោះកសិករដែលចូលរួម។',
  'farmland_area': 'តំបន់ដីស្រែចំការ',
  'farmland_area_input_hint': 'សូម​ចូល​តំបន់​ដី​ស្រែ​ចម្ការ (ha)',
  'farmland_area_unit': 'ha',
  'take_picture': 'ថតរូប',
  'latitude': 'រយៈទទឹង',
  'longitude': 'រយៈបណ្តោយ',
  'record_title': 'កត់ត្រាវា',
  'record_pump': 'កំណត់ត្រាស្រោចទឹក។',
  'record_drain_water': 'ការបង្ហូរទឹក',
  'record_fertilizer': 'កំណត់ត្រាជី',
  'record_pesticide': 'កំណត់ត្រាថ្នាំសំលាប់សត្វល្អិត',
  'record_harvest': 'កំណត់ត្រាទិន្នផលប្រមូលផល',
  'record_diary': 'កំណត់ហេតុប្រចាំថ្ងៃ',
  'record_diary_option': 'កំណត់ចំណាំប្រចាំថ្ងៃ (ជាជម្រើស)',
  'record_diary_hint': 'បញ្ចូលមាតិកា (រហូតដល់ 3000 តួអក្សរ)',
  'record_done': 'ការថតបានបញ្ចប់',
  'record_calendar_lunar': 'ការបង្ហាញប្រតិទិនតាមច័ន្ទគតិ',
  'record_calendar_event_pump_on': 'ទឹកចូល',
  'record_calendar_event_pump_off': 'ទឹកចេញ',
  'record_calendar_event_start_drain_water': 'ចាប់ផ្តើមបង្ហូរទឹក',
  'record_calendar_event_end_drain_water': 'បញ្ចប់ការបង្ហូរទឹក',
  'record_input_data': 'បញ្ចូលព័ត៌មានកសិកម្ម',
  'my_page_name_title': 'លោក/លោកស្រី',
  'my_page_hello': 'សួស្តី!',
  'my_page_menu_awd_change': 'ការផ្លាស់ប្តូរកាលវិភាគសម្រកទឹក',
  'my_page_menu_faq': 'សំណួរគេសួរញឹកញាប់',
  'my_page_menu_terms_service': 'ល័ក្ខខ័ណ្ឌនៃសេវាកម្ម',
  'my_page_menu_terms_privacy': 'គោលការណ៍ឯកជនភាព',
  'my_page_menu_qna': 'ទាក់ទងមកយើងខ្ញុំ',
  'my_page_menu_awd_edu': 'សម្ភារៈសិក្សា AWD',
  'my_page_menu_tutorial': 'វីដេអូបង្រៀន',
  'my_page_menu_language': 'Language',
  'my_page_menu_app_version': 'ព័ត៌មានអំពីកំណែ',
  'my_page_menu_logout': 'ចេញ',
  'my_page_menu_withdraw': 'លុបគណនី',
  'progress_title': 'វឌ្ឍនភាព AWD',
  'progress_overall': 'ដំណើរការទាំងមូល',
  'progress_planting': 'ដាំ',
  'progress_1st_awd': 'ទី 1 AWD',
  'progress_2nd_awd': 'ទី 2 AWD',
  'progress_harvest': 'ការប្រមូលផល',
  'progress_record_pump': 'កំណត់ត្រាស្រោចទឹក។',
  'progress_record_photo': 'ថតរូប',
  'progress_finish_project': 'បញ្ចប់គម្រោង',
  'progress_finish_project_popup_message': 'តើអ្នកចង់បញ្ចប់គម្រោងទេ?',
  'input': 'បញ្ចូល',
  'logout_desc': 'តើអ្នកចង់ចេញពីគណនីទេ?',
  'logout': 'ចេញ',
  'withdraw': 'លុបគណនី',
  'withdraw_desc': 'តើអ្នកចង់លុបគណនីរបស់អ្នកទេ?',
  'input_rice_planting_title': 'បញ្ចូលព័ត៌មានកសិកម្ម',
  'input_rice_planting_date': 'សូមជ្រើសរើសកាលបរិច្ឆេទស្ទូងស្រូវ។',
  'input_rice_planting_date_hint': 'សូមជ្រើសរើសកាលបរិច្ឆេទស្ទូងស្រូវ។',
  'input_rice_planting_type': 'សូមជ្រើសរើសវិធីស្ទូងស្រូវ។',
  'input_rice_planting_type_hint': 'សូមជ្រើសរើសវិធីស្ទូងស្រូវ។',
  'input_rice_planting_rice_cultivar': 'សូមជ្រើសរើសពូជស្រូវ។',
  'input_rice_planting_rice_cultivar_hint': 'សូមជ្រើសរើសពូជស្រូវ។',
  'input_pump_planting_title': 'ចុះឈ្មោះកាលវិភាគស្រោចទឹក។',
  'input_pump_planting_index': 'ការស្រោចទឹក បើក/បិទ កាលវិភាគទី {count}',
  'input_pump_planting_hint': 'ជ្រើសរើសកាលបរិច្ឆេទស្រោចទឹក។',
  'input_pump_error_date': 'សូមពិនិត្យមើលកាលវិភាគ។ \n បញ្ចូលកាលវិភាគតាមលំដាប់លំដោយ។',
  'input_pump_error_maximum': 'អ្នកអាចបន្ថែមបានត្រឹមតែ 5 កាលវិភាគប៉ុណ្ណោះ។',
  'input_drain_water_planting_title': 'ចុះឈ្មោះកាលវិភាគបង្ហូរទឹក',
  'input_drain_water_planting_select_hint': 'ជ្រើសរើសកាលបរិច្ឆេទបង្ហូរ',
  'input_drain_water_planting_index': 'កាលវិភាគនៃការបង្ហូរ {count}',
  'record_confirm_message': 'ការផ្លាស់ប្តូរមិនត្រូវបានអនុញ្ញាតទេបន្ទាប់ពីចូល។\n តើអ្នកចង់បន្តទេ?',
  'record_pesticide_title': 'សូមកត់ត្រាការប្រើប្រាស់ថ្នាំសម្លាប់សត្វល្អិត!',
  'record_pesticide_input_hint': 'សូមជ្រើសរើសប្រភេទថ្នាំសំលាប់សត្វល្អិត។',
  'record_pesticide_type': 'ប្រភេទថ្នាំសំលាប់សត្វល្អិត',
  'record_pesticide_usage': 'ការប្រើប្រាស់ថ្នាំសំលាប់សត្វល្អិត',
  'record_pesticide_usage_input_hint': 'សូមបញ្ចូលការប្រើប្រាស់ថ្នាំសំលាប់សត្វល្អិត។',
  'record_harvest_title': 'សូមកត់ត្រាទិន្នផល!',
  'record_harvest_input_hint': 'សូមបញ្ចូលទិន្នផល។',
  'record_fertilizer_title': 'សូមកត់ត្រាការប្រើប្រាស់ជី!',
  'record_fertilizer_type': 'ប្រភេទជី',
  'record_fertilizer_input_hint': 'សូមជ្រើសរើសប្រភេទជី។',
  'record_fertilizer_usage': 'ការប្រើប្រាស់ជី',
  'record_fertilizer_usage_input_hint': 'សូមបញ្ចូលការប្រើប្រាស់ជី។',
  'record_drain_water_title': 'ការផ្ទៀងផ្ទាត់រូបថតបង្ហូរទឹក',
  'harvest': 'ទិន្នផល',
  'cannot_modified': 'វាមិនអាចកែប្រែបានទេ។',
  'error_select_date_message': 'សូមជ្រើសរើសកាលបរិច្ឆេទ។',
  'permission_error_message': 'សូមពិនិត្យមើលការអនុញ្ញាត។',
  'move_setting': 'ចូលទៅកាន់ការកំណត់',
  'time': 'ពេលវេលា',
  'take_picture2': 'ថតរូប',
  'record_pump_on_message': 'តើអ្នកចង់ប្តូរស្ថានភាពទៅជាបើកទេ?\n ការផ្លាស់ប្តូរនឹងមិនត្រូវបានអនុញ្ញាតនៅពេលក្រោយទេ។',
  'record_pump_off_message': 'តើអ្នកចង់ប្តូរស្ថានភាពទៅជាបិទទេ?\n ការផ្លាស់ប្តូរនឹងមិនត្រូវបានអនុញ្ញាតនៅពេលក្រោយទេ។',
  'change_request_history_title': 'ផ្លាស់ប្តូរប្រវត្តិសំណើ',
  'change_request_history_empty': 'រកមិនឃើញសំណើផ្លាស់ប្តូរទេ។',
  'tab_home': 'ទំព័រដើម',
  'tab_progress': 'ស្ថានភាពវឌ្ឍនភាព',
  'tab_mypage': 'ទំព័ររបស់ខ្ញុំ',
  'record_diary_empty': 'មិនមានកំណត់ហេតុត្រូវបានសរសេរទេ។',
  'schedule_change_request_title': 'ផ្លាស់ប្តូរកាលវិភាគ',
  'schedule_change_request_reason': 'ហេតុផលសម្រាប់ការផ្លាស់ប្តូរ',
  'schedule_change_request_reason_hint': 'បញ្ចូលមាតិកា (រហូតដល់ 3,000 តួអក្សរ)',
  'progress_error_message': 'សូមពិនិត្យមើលវឌ្ឍនភាព។',
  'record_diary_confirm_message': 'តើអ្នកចង់សរសេរកំណត់ហេតុទេ?',
  'my_page_menu_notification': 'ការកំណត់ការជូនដំណឹង',
  'exception_unexpected': 'កំហុសមិនស្គាល់បានកើតឡើង។',
  'exception_network': 'សូមពិនិត្យមើលការតភ្ជាប់បណ្តាញរបស់អ្នក។',
  'exception_not_found_user': 'រកមិនឃើញព័ត៌មានអ្នកប្រើប្រាស់ទេ។',
  'my_page_menu_pump_change': 'ការផ្លាស់ប្តូរតារាងវារទឹក',
  'my_page_menu_pump_change_history': 'ប្រវត្តិការផ្លាស់ប្តូរតារាងវារទឹក',
  'farmland_status_pending': 'រង់ចាំការអនុម័ត',
  'farmland_status_rejected': 'ការអនុម័តត្រូវបានបដិសេធ',
  'farmland_status_photo_required': 'ត្រូវការរូបថត',
  'farmland_status_approved': 'ការអនុម័តបានបញ្ចប់',
  'farmland_status_completed': 'បញ្ចប់ភារកិច្ច',
  'change_request_status_pending': 'រង់ចាំការអនុម័ត',
  'change_request_status_approved': 'ការអនុម័តបានបញ្ចប់',
  'change_request_status_rejected': 'ការអនុម័តត្រូវបានបដិសេធ',
  'hand_planting': 'ដាំដំណាំដោយដៃ',
  'machine_planting': 'ដាំដំណាំដោយម៉ាស៊ីន',
  'my_page_menu_awd_change_history': 'ប្រវត្តិការផ្លាស់ប្តូរទីតាំងកាលវិភាគសម្រកទឹក',
};
