final viString = {
  'login_desc': 'Bắt đầu nông nghiệp số\nGhi chép dễ dàng với Haimdall',
  'login_desc_sns': 'Đăng nhập bằng tài khoản mạng xã hội (SNS)',
  'select_language': 'Language',
  'select_language_title': 'Chọn Ngôn ngữ',
  'select_language_error_message': 'Hãy chọn Quốc gia và Ngôn ngữ!',
  'ok': 'Xác nhận',
  'cancel': 'Hủy',
  'terms_page_title': 'Đồng ý với các điều khoản thông tin cá nhân',
  'terms_check_required': 'Đồng ý xem điều khoản/Chính sách xử lý thông tin cá nhân (Bắt buộc)',
  'terms_check_service': 'Điều khoản sử dụng dịch vụ (Bắt buộc)',
  'terms_next_error_message': 'Vui lòng đồng ý với điều khoản trước khi tiếp tục.',
  'terms_privacy': 'Chính sách xử lý thông tin cá nhân',
  'terms_service': 'Điều khoản sử dụng',
  'next': 'Tiếp theo',
  'awd_title': 'Tôi sẽ cho bạn biết thêm về Tưới ướt khô xen kẽ (AWD)!',
  'signup_title': 'Nhập thông tin đăng ký',
  'signup_input_name': 'Vui lòng nhập tên.',
  'signup_input_name_hint': 'Nhập tên',
  'signup_input_phone': 'Vui lòng nhập số điện thoại',
  'signup_input_phone_hint': 'Nhập số điện thoại',
  'signup_input_email': 'Vui lòng nhập địa chỉ email.',
  'signup_input_email_hint': 'Nhập email',
  'input_error': 'Vui lòng điền tất cả các hạng mục bắt buộc.',
  'input_warning_back': 'Nội dung bạn đã viết sẽ bị xóa.\n Bạn có muốn tiếp tục không?',
  'yes': 'Có',
  'no': 'Không',
  'signup_project_title': 'Chọn dự án',
  'signup_project_desc': 'Vui lòng chọn dự án mong muốn.',
  'signup_project_desc_point': '(Chỉ có thể chọn một.)',
  'signup_project_select_hint': 'Vui lòng chọn dự án.',
  'signup_waiting_desc1': 'Vui lòng đợi\nmột chút!',
  'signup_waiting_desc2': 'Đang chờ phê duyệt của quản trị viên!',
  'signup_denied_desc1': 'Phê duyệt của quản trị viên đã bị từ chối',
  'signup_denied_desc2': 'Vui lòng đăng ký lại.',
  'signup_denied_request_approve': 'Yêu cầu kiểm duyệt lại.',
  'tutorial_video': 'Xem video hướng dẫn',
  'skip': 'Bỏ qua',
  'farmland_list_title': 'Danh sách đất nông nghiệp',
  'farmland_add': 'Thêm đất nông nghiệp',
  'farmland_add_title': 'Nhập thông tin đất nông nghiệp',
  'farmland_owner_name': 'Tên người dân tham gia',
  'farmland_owner_name_desc': '(Không thể thay đổi. Vui lòng điền cẩn thận)',
  'farmland_owner_name_input_hint': 'Vui lòng nhập tên nông dân tham gia.',
  'farmland_area': 'Diện tích đất nông nghiệp',
  'farmland_area_input_hint': 'Vui lòng nhập diện tích đất nông nghiệp (ha)',
  'farmland_area_unit': 'ha',
  'take_picture': 'Chụp ảnh',
  'latitude': 'Vĩ độ',
  'longitude': 'Kinh độ',
  'record_title': 'Ghi chép lại.',
  'record_pump': 'Ghi chép việc tưới nước',
  'record_drain_water': 'Rút nước',
  'record_fertilizer': 'Ghi chép phân bón ',
  'record_pesticide': 'Ghi chép thuốc bảo vệ thực vật',
  'record_harvest': 'Ghi chép sản lượng',
  'record_diary': 'Nhập nhật ký',
  'record_diary_option': 'Ghi chú hàng ngày (Tùy chọn)',
  'record_diary_hint': 'Nhập nội dung (Tối đa 3000 ký tự)',
  'record_done': 'Hoàn tất ghi chép',
  'record_calendar_lunar': 'Hiển thị lịch âm',
  'record_calendar_event_pump_on': 'Bật Tưới nước',
  'record_calendar_event_pump_off': 'Tắt Tưới nước',
  'record_calendar_event_start_drain_water': 'Bắt đầu rút nước',
  'record_calendar_event_end_drain_water': 'Dừng rút nước',
  'record_input_data': 'Nhập thông tin canh tác',
  'my_page_name_title': 'Anh/Chị',
  'my_page_hello': 'Xin chào',
  'my_page_menu_awd_change': 'Thay Đổi Lịch Rút Nước',
  'my_page_menu_faq': 'Câu hỏi thường gặp',
  'my_page_menu_terms_service': 'Điều khoản sử dụng dịch vụ',
  'my_page_menu_terms_privacy': 'Chính sách xử lý thông tin cá nhân',
  'my_page_menu_qna': 'Liên hệ chúng tôi',
  'my_page_menu_awd_edu': 'Tài liệu đào tạo AWD',
  'my_page_menu_tutorial': 'hướng dẫn',
  'my_page_menu_language': 'Language',
  'my_page_menu_app_version': 'Thông tin phiên bản',
  'my_page_menu_logout': 'Đăng xuất',
  'my_page_menu_withdraw': 'Hủy tư cách thành viên',
  'progress_title': 'Tình hình thực hiện Tưới ướt khô xen kẽ',
  'progress_overall': 'Toàn bộ quá trình',
  'progress_planting': 'Xuống giống',
  'progress_1st_awd': 'AWD lần 1',
  'progress_2nd_awd': 'AWD lần 2',
  'progress_harvest': 'Thu hoạch',
  'progress_record_pump': 'Ghi chép việc tưới nước',
  'progress_record_photo': 'Chụp ảnh',
  'progress_finish_project': 'Kết thúc dự án',
  'progress_finish_project_popup_message': 'Bạn có muốn kết thúc\n dự án không?',
  'input': 'Nhập',
  'logout_desc': 'Bạn có muốn đăng xuất không?',
  'logout': 'Đăng xuất',
  'withdraw': 'Xóa tài khoản',
  'withdraw_desc': 'Bạn có muốn xóa tài khoản không?',
  'input_rice_planting_title': 'Nhập thông tin canh tác',
  'input_rice_planting_date': 'Vui lòng chọn ngày xuống giống.',
  'input_rice_planting_date_hint': 'Vui lòng chọn ngày xuống giống.',
  'input_rice_planting_type': 'Vui lòng chọn phương pháp xuống giống.',
  'input_rice_planting_type_hint': 'Vui lòng chọn phương pháp xuống giống.',
  'input_rice_planting_rice_cultivar': 'Vui lòng chọn giống lúa.',
  'input_rice_planting_rice_cultivar_hint': 'Vui lòng chọn giống lúa.',
  'input_pump_planting_title': 'Đăng lý lịch tưới nước',
  'input_pump_planting_index': 'Lịch TĂT/BẬT việc tưới nước lần {count}',
  'input_pump_planting_hint': 'Vui lòng chọn lịch tưới nước',
  'input_pump_error_date': 'Vui lòng xác nhận lịch.\n Vui lòng nhập lịch theo thứ tự.',
  'input_pump_error_maximum': 'Bạn chỉ có thể thêm tối đa 05 lịch.',
  'input_drain_water_planting_title': 'Đăng ký lịch rút nước',
  'input_drain_water_planting_select_hint': 'Chọn ngày rút nước',
  'input_drain_water_planting_index': 'Lịch rút nước lần {count}',
  'record_confirm_message': 'Sau khi nhập sẽ không thể thay đổi.\nBạn có muốn tiếp tục không?',
  'record_pesticide_title': 'Vui lòng ghi chép thông tin thuốc bảo vệ thực vật!',
  'record_pesticide_input_hint': 'Vui lòng chọn loại thuốc bảo vệ thực vật.',
  'record_pesticide_type': 'Loại thuốc bảo vệ thực vật',
  'record_pesticide_usage': 'Lượng sử dụng thuốc bảo vệ thực vật',
  'record_pesticide_usage_input_hint': 'Vui lòng nhập lượng sử dụng thuốc bảo vệ thực vật.',
  'record_harvest_title': 'Vui lòng ghi chép sản lượng thu hoạch!',
  'record_harvest_input_hint': 'Vui lòng nhập sản lượng thu hoạch.',
  'record_fertilizer_title': 'Vui lòng ghi chép lượng phân bón sử dụng!',
  'record_fertilizer_type': 'Loại phân bón',
  'record_fertilizer_input_hint': 'Vui lòng chọn loại phân bón.',
  'record_fertilizer_usage': 'Lượng sử dụng phân bón',
  'record_fertilizer_usage_input_hint': 'Vui lòng nhập lượng sử dụng phân bón.',
  'record_drain_water_title': 'Xác nhận ảnh tháo nước',
  'harvest': 'Sản lượng thu hoạch',
  'cannot_modified': 'Không thể sửa đổi.',
  'error_select_date_message': 'Vui lòng chọn ngày.',
  'permission_error_message': 'Vui lòng kiểm tra quyền.',
  'move_setting': 'Di chuyển đến cài đặt',
  'time': 'Thời gian',
  'take_picture2': 'Chụp ảnh',
  'record_pump_on_message': 'Bạn có muốn chuyển sang trạng thái bật không?\n Bạn sẽ không thể thay đổi nội dung sau khi nhập.',
  'record_pump_off_message': 'Bạn có muốn chuyển sang trạng thái tắt không?\n Bạn sẽ không thể thay đổi nội dung sau khi nhập.',
  'change_request_history_title': 'Lịch sử yêu cầu thay đổi',
  'change_request_history_empty': 'Không có nội dung yêu cầu thay đổi.',
  'tab_home': 'Trang chủ',
  'tab_progress': 'Tình hình tiến độ',
  'tab_mypage': 'Trang cá nhân',
  'record_diary_empty': 'Không có nhật ký nào được tạo.',
  'schedule_change_request_title': 'Thay đổi lịch trình',
  'schedule_change_request_reason': 'Lý do thay đổi',
  'schedule_change_request_reason_hint': 'Nhập nội dung (tối đa 3.000 ký tự)',
  'progress_error_message': 'Vui lòng kiểm tra tình hình tiến độ.',
  'record_diary_confirm_message': 'Bạn có muốn viết nhật ký không?',
  'my_page_menu_notification': 'Cài đặt thông báo',
  'exception_unexpected': 'Đã xảy ra lỗi không xác định.',
  'exception_network': 'Vui lòng kiểm tra trạng thái kết nối mạng.',
  'exception_not_found_user': 'Không thể tìm thấy thông tin người dùng.',
  'my_page_menu_pump_change': 'Thay đổi lịch tưới nước',
  'my_page_menu_pump_change_history': 'Lịch sử thay đổi lịch tưới nước',
  'farmland_status_pending': 'Chờ phê duyệt',
  'farmland_status_rejected': 'Từ chối phê duyệt',
  'farmland_status_photo_required': 'Cần ảnh',
  'farmland_status_approved': 'Phê duyệt hoàn tất',
  'farmland_status_completed': 'Hoàn thành nhiệm vụ',
  'change_request_status_pending': 'Chờ phê duyệt',
  'change_request_status_approved': 'Phê duyệt hoàn tất',
  'change_request_status_rejected': 'Từ chối phê duyệt',
  'hand_planting': 'Trồng bằng tay',
  'machine_planting': 'Trồng bằng máy',
  'my_page_menu_awd_change_history': 'Lịch Sử Thay Đổi Lịch Rút Nước',
};
