# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc "Push a new Production build to TestFlight"
    lane :production do
        match(
            type: "appstore",
            readonly: is_ci,
            verbose: true
  	    )

        build_app(
          workspace: "Runner.xcworkspace",
          configuration: "Release-Production",
          scheme: "Production",
          silent: true,
          clean: true
        )

        upload_to_testflight(
            skip_waiting_for_build_processing: true,
            apple_id: "6670794584"
        )
  end
end
