final bdString = {
  'login_desc': 'ডিজিটাল কৃষির সূচনা\nহাইমডাল দিয়ে সহজেই রেকর্ড করুন!',
  'login_desc_sns': 'SNSএসএনএস অ্যাকাউন্ট দিয়ে লগইন করুন',
  'select_language': 'Language',
  'select_language_title': 'ভাষা নির্বাচন',
  'select_language_error_message': 'একটি দেশ এবং ভাষা নির্বাচন করুন',
  'ok': 'নিশ্চিত করুন',
  'cancel': 'বাতিল করুন',
  'terms_page_title': 'গোপনীয়তা নীতিতে রাজী হন',
  'terms_check_required': 'শর্তাবলী/গোপনীয়তা নীতিতে রাজী হন (বাধ্যতামূলক)',
  'terms_check_service': 'পরিষেবার শর্তাবলী (বাধ্যতামূলক)',
  'terms_next_error_message': 'শর্তাবলীতে সম্মত হওয়ার পর অনুগ্রহ করে সামনে অগ্রসর হোন।',
  'terms_privacy': 'গোপনীয়তা নীতি',
  'terms_service': 'নিয়ম ও শর্তাবলী',
  'next': 'পরবর্তী',
  'awd_title': 'আমাকে AWD সম্পর্কে আরও বলতে দিন!',
  'signup_title': 'সাইন আপ সংক্রান্ত তথ্য লিখুন',
  'signup_input_name': 'আপনার নাম লিখুন.',
  'signup_input_name_hint': 'নাম ইনপুট',
  'signup_input_phone': 'আপনার মোবাইল ফোন নম্বর লিখুন.',
  'signup_input_phone_hint': 'মোবাইল ফোন নম্বর ইনপুট',
  'signup_input_email': 'আপনার ইমেল-এড্রেস লিখুন.',
  'signup_input_email_hint': 'ইমেল ইনপুট',
  'input_error': 'প্রয়োজনীয় সব ক্ষেত্র পূরণ করুন.',
  'input_warning_back': 'আপনার লিখিত বিষয়বস্তু মুছে ফেলা হবে।\nআপনি কি চালিয়ে যেতে চান?',
  'yes': 'হ্যাঁ',
  'no': 'না',
  'signup_project_title': 'প্রকল্প নির্বাচন করুন',
  'signup_project_desc': 'আপনার কাঙ্খিত প্রকল্পটি নির্বাচন করুন',
  'signup_project_desc_point': '(শুধুমাত্র একক নির্বাচন অনুমোদিত।)',
  'signup_project_select_hint': 'একটি প্রকল্প নির্বাচন করুন.',
  'signup_waiting_desc1': 'কিছুক্ষণ\nঅপেক্ষা করুন!',
  'signup_waiting_desc2': 'এডমিন থেকে অনুমোদন প্রক্রিয়াধীন!',
  'signup_denied_desc1': 'এডমিনের অনুমোদন \nপ্রত্যাখ্যান করা হয়েছে।',
  'signup_denied_desc2': 'আবার নিবন্ধন করুন.',
  'signup_denied_request_approve': 'পুনরায় অনুমোদনের অনুরোধ',
  'tutorial_video': 'টিউটোরিয়াল ভিডিও দেখুন',
  'skip': 'এড়িয়ে যান',
  'farmland_list_title': 'কৃষিজমির তালিকা',
  'farmland_add': 'কৃষি জমি যোগ করুন',
  'farmland_add_title': 'কৃষি জমির তথ্য লিখুন',
  'farmland_owner_name': 'অংশগ্রহণকারী কৃষকের নাম',
  'farmland_owner_name_desc': '(পরিবর্তন অনুমোদিত নয়। দয়া করে এটি সাবধানে পূরণ করুন!)',
  'farmland_owner_name_input_hint': 'অংশগ্রহণকারী কৃষকের নাম লিখুন.',
  'farmland_area': 'কৃষিজমি এলাকা',
  'farmland_area_input_hint': 'অনুগ্রহ করে কৃষিজমির এলাকা (হেক্টর) লিখুন।',
  'farmland_area_unit': 'হেক্টর',
  'take_picture': 'একটি ছবি তুলুন',
  'latitude': 'অক্ষাংশ',
  'longitude': 'দ্রাঘিমাংশ',
  'record_title': 'এটা রেকর্ড করুন.',
  'record_pump': 'জল দেওয়ার রেকর্ড',
  'record_drain_water': 'পানি নিষ্কাশন',
  'record_fertilizer': 'সার রেকর্ড',
  'record_pesticide': 'কীটনাশক রেকর্ড',
  'record_harvest': 'ফলন রেকর্ড',
  'record_diary': 'ডায়েরি এন্ট্রি',
  'record_diary_option': 'দৈনিক নোট (ঐচ্ছিক)',
  'record_diary_hint': 'বিষয়বস্তু লিখুন (3000 অক্ষর পর্যন্ত)',
  'record_done': 'রেকর্ডিং সম্পূর্ণ',
  'record_calendar_lunar': 'চন্দ্র ক্যালেন্ডার প্রদর্শন',
  'record_calendar_event_pump_on': 'জল দেওয়া',
  'record_calendar_event_pump_off': 'জল বের করা',
  'record_calendar_event_start_drain_water': 'জল নিষ্কাশন শুরু',
  'record_calendar_event_end_drain_water': 'জল নিষ্কাশন শেষ',
  'record_input_data': 'কৃষি তথ্য লিখুন',
  'my_page_name_title': 'স্যার/ম্যাডাম',
  'my_page_hello': 'হ্যালো!',
  'my_page_menu_awd_change': 'জল নিষ্কাশন সময়সূচী পরিবর্তন',
  'my_page_menu_faq': 'প্রায়শই জিজ্ঞাসিত প্রশ্নাবলী',
  'my_page_menu_terms_service': 'পরিষেবার শর্তাবলী',
  'my_page_menu_terms_privacy': 'গোপনীয়তা নীতি',
  'my_page_menu_qna': 'আমাদের সাথে যোগাযোগ করুন',
  'my_page_menu_awd_edu': 'AWD শিক্ষাগত উপকরণ',
  'my_page_menu_tutorial': 'টিউটোরিয়াল',
  'my_page_menu_language': 'Language',
  'my_page_menu_app_version': 'সংস্করণ তথ্য',
  'my_page_menu_logout': 'লগআউট',
  'my_page_menu_withdraw': 'অ্যাকাউন্ট মুছুন',
  'progress_title': 'AWD অগ্রগতি',
  'progress_overall': 'পুরো প্রক্রিয়া',
  'progress_planting': 'রোপণ',
  'progress_1st_awd': '1ম AWD',
  'progress_2nd_awd': '২য় AWD',
  'progress_harvest': 'ফসল',
  'progress_record_pump': 'জল দেওয়ার রেকর্ড',
  'progress_record_photo': 'ছবি তোলা',
  'progress_finish_project': 'প্রকল্প শেষ করুন',
  'progress_finish_project_popup_message': 'আপনি কি প্রকল্পটি শেষ করতে চান?',
  'input': 'প্রবেশ করুন',
  'logout_desc': 'আপনি কি লগ আউট করতে চান?',
  'logout': 'লগ আউট করুন',
  'withdraw': 'অ্যাকাউন্ট মুছুন',
  'withdraw_desc': 'আপনি কি আপনার অ্যাকাউন্ট মুছতে চান?',
  'input_rice_planting_title': 'কৃষি তথ্য লিখুন',
  'input_rice_planting_date': 'অনুগ্রহ করে ধান রোপনের তারিখ নির্বাচন করুন।',
  'input_rice_planting_date_hint': 'অনুগ্রহ করে ধান রোপনের তারিখ নির্বাচন করুন।',
  'input_rice_planting_type': 'ধান রোপন পদ্ধতি নির্বাচন করুন.',
  'input_rice_planting_type_hint': 'ধান রোপন পদ্ধতি নির্বাচন করুন.',
  'input_rice_planting_rice_cultivar': 'ধানের জাত নির্বাচন করুন।',
  'input_rice_planting_rice_cultivar_hint': 'ধানের জাত নির্বাচন করুন।',
  'input_pump_planting_title': 'জল দেওয়ার সময়সূচী নিবন্ধন করুন',
  'input_pump_planting_index': 'জল দেওয়া চালু/বন্ধ {count}তম সময়সূচী৷',
  'input_pump_planting_hint': 'জল দেওয়ার তারিখ নির্বাচন করুন',
  'input_pump_error_date': 'সময়সূচী চেক করুন. \n ক্রমানুসারে সময়সূচী লিখুন।',
  'input_pump_error_maximum': 'আপনি শুধুমাত্র 5 পর্যন্ত সময়সূচী যোগ করতে পারেন।',
  'input_drain_water_planting_title': 'ড্রেনিং সময়সূচী নিবন্ধন করুন',
  'input_drain_water_planting_select_hint': 'নিষ্কাশনের তারিখ নির্বাচন করুন',
  'input_drain_water_planting_index': 'ড্রেনিং {count}তম সময়সূচী',
  'record_confirm_message': 'প্রবেশের পরে পরিবর্তন অনুমোদিত নয়৷\nআপনি কি এগিয়ে যেতে চান?',
  'record_pesticide_title': 'কীটনাশক ব্যবহার রেকর্ড করুন!',
  'record_pesticide_input_hint': 'অনুগ্রহ করে কীটনাশকের ধরন নির্বাচন করুন।',
  'record_pesticide_type': 'কীটনাশকের ধরন',
  'record_pesticide_usage': 'কীটনাশক ব্যবহার',
  'record_pesticide_usage_input_hint': 'অনুগ্রহ করে কীটনাশক ব্যবহার লিখুন।',
  'record_harvest_title': 'ফলন রেকর্ড করুন!',
  'record_harvest_input_hint': 'ফলন লিখুন.',
  'record_fertilizer_title': 'দয়া করে সার ব্যবহার রেকর্ড করুন!',
  'record_fertilizer_type': 'সারের প্রকার',
  'record_fertilizer_input_hint': 'অনুগ্রহ করে সারের প্রকার নির্বাচন করুন।',
  'record_fertilizer_usage': 'সার ব্যবহার',
  'record_fertilizer_usage_input_hint': 'অনুগ্রহ করে সার ব্যবহার লিখুন।',
  'record_drain_water_title': 'জল নিষ্কাশন ফটো যাচাই',
  'harvest': 'ফলন',
  'cannot_modified': 'পরিবর্তন করা যাবে না।',
  'error_select_date_message': 'একটি তারিখ নির্বাচন করুন.',
  'permission_error_message': 'অনুমতি চেক করুন.',
  'move_setting': 'সেটিংসে যান',
  'time': 'সময়',
  'take_picture2': 'ছবি তুলুন',
  'record_pump_on_message': 'আপনি কি স্থিতি পরিবর্তন করতে চান?\n পরে পরিবর্তনের অনুমতি দেওয়া হবে না।',
  'record_pump_off_message': 'আপনি কি স্থিতিটিকে বন্ধে পরিবর্তন করতে চান?\nপরে পরিবর্তনগুলি অনুমোদিত হবে না৷',
  'change_request_history_title': 'অনুরোধের ইতিহাস পরিবর্তন করুন',
  'change_request_history_empty': 'কোনো পরিবর্তনের অনুরোধ পাওয়া যায়নি।',
  'tab_home': 'বাড়ি',
  'tab_progress': 'অগ্রগতি',
  'tab_mypage': 'আমার পৃষ্ঠা',
  'record_diary_empty': 'কোন লগ লেখা হয় নাই',
  'schedule_change_request_title': 'সময়সূচী পরিবর্তন করুন',
  'schedule_change_request_reason': 'পরিবর্তনের কারণ',
  'schedule_change_request_reason_hint': 'বিষয়বস্তু লিখুন (3,000 অক্ষর পর্যন্ত)',
  'progress_error_message': 'অগ্রগতি চেক করুন.',
  'record_diary_confirm_message': 'আপনি একটি লগ লিখতে চান?',
  'my_page_menu_notification': 'বিজ্ঞপ্তি সেটিংস',
  'exception_unexpected': 'একটি অজানা ত্রুটি ঘটেছে.',
  'exception_network': 'আপনার নেটওয়ার্ক সংযোগ পরীক্ষা করুন.',
  'exception_not_found_user': 'ব্যবহারকারীর তথ্য পাওয়া যাচ্ছে না।',
  'my_page_menu_pump_change': 'সেচ সময়সূচি পরিবর্তন',
  'my_page_menu_pump_change_history': 'সেচ সময়সূচি পরিবর্তনের ইতিহাস',
  'farmland_status_pending': 'অনুমোদনের জন্য অপেক্ষারত',
  'farmland_status_rejected': 'অনুমোদন প্রত্যাখ্যান',
  'farmland_status_photo_required': 'ছবি প্রয়োজন',
  'farmland_status_approved': 'অনুমোদন সম্পন্ন',
  'farmland_status_completed': 'কাজ সম্পন্ন',
  'change_request_status_pending': 'অনুমোদনের জন্য অপেক্ষারত',
  'change_request_status_approved': 'অনুমোদন সম্পন্ন',
  'change_request_status_rejected': 'অনুমোদন প্রত্যাখ্যান',
  'hand_planting': 'হাত দিয়ে রোপণ',
  'machine_planting': 'মেশিন দিয়ে রোপণ',
  'my_page_menu_awd_change_history': 'পানি নিষ্কাশন সময়সূচী পরিবর্তনের ইতিহাস',
};
